### ISSUE TITLE
prettier clash with eslint autofix

### ISSUE THREAD

**Issue by ackvf** [Jakub41/Nasa-app#10]
This is giving me hard time. I wonder, does it also happen to you?

![nasa-app-editor-formatting_o](https://user-images.githubusercontent.com/2313018/84145592-767e7900-aa5a-11ea-8c76-329879026039.gif)

I had to remove the workspace .vscode settings to get rid of this

**Comment by Jakub41** [comment]
Hey, can you explain what issues is giving it to you?

The. vscode i will ignore it by the way but in general the only issue I have with eslint is on windows machines.

Deleted vscode settings eslint working good for you?

Thank you

**Comment by ackvf** [comment]
When I save the file, the autosave will first format with eslint, then with prettier which in return breaks the eslint rules.

**Comment by Jakub41** [comment]
I see but I had no issues actually. So better to delete the vscode settings to avoid those issues then? -- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 6/9/20, 14:42 "Vítězslav Ackermann Ferko" <notifications@github.com> wrote:

   
  When I save the file, the autosave will first format with eslint, then with prettier which in return breaks the eslint rules.

**Comment by Jakub41** [comment]
By the way I'm new to eslint and I used guides online to set it up. If you have any suggestions how to setup it correctly I will be glad to hear 😁👍-- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 6/9/20, 14:42 "Vítězslav Ackermann Ferko" <notifications@github.com> wrote:

   
  When I save the file, the autosave will first format with eslint, then with prettier which in return breaks the eslint rules.

**Comment by ackvf** [comment]
It's generally better to not put IDE settings into workspace, especially those which depend on dev's preference - like the IDE layout. Some settings however do make sense to be "enforced", such as formatting, but then it is much better to include formatting in a build step or commit hook (using [husky](https://www.npmjs.com/package/husky)).

**Comment by Jakub41** [comment]
Thank you,
I set it up, Husky in my package.json is that fine or I need to add some extra there I missed actually? 

I will delete that .vscode as I followed a guide which was saying to add there some rules actually but it could be I did some mistakes or mixed too many things together
